### ISSUE TITLE
General question about your modified uECC library.

### ISSUE THREAD

**Issue by ismyhc** [OracleChain/chainkit#1]
https://github.com/OracleChain/chainkit/blob/aee9a63685e04320cf30869683a348637ddd88c2/Crypto/uECC.c#L2810-L2838

Hi, I apologize if this this is out of line, but I've been playing around trying to understand EOS and crypto in general and I'm at the stage of trying to create / sign transaction and push to the block chain. Im using what looks like the same ecc library that you have here. uECC (micro-ecc), but I've noticed that you have added a few extra functions one being `uECC_sign_forbc(`. So my question is, will I need to do something similar or can I sign an EOS transaction using the already present `uECC_sign(` function. Im a swift developer so I have the micro-ecc library pulled into my swift project.

Any insight much appreciated :)

Thanks,
Jacob

**Comment by spartucus** [comment]
Hi @ismyhc . The reason we are using `uECC_sign_forbc` instead of `uECC_sign` function is that we added two filters to fulfill EOS's crypto standard.
https://github.com/OracleChain/chainkit/blob/aee9a63685e04320cf30869683a348637ddd88c2/Crypto/uECC.c#L2827-L2830
and
https://github.com/OracleChain/chainkit/blob/aee9a63685e04320cf30869683a348637ddd88c2/Crypto/uECC.c#L2831-L2833

My suggest is that you should not just use uECC straightforward.
